#cloud-config
local-hostname: ${hostname}
instance-id: ${hostname}
wait-on-network:
  ipv4: false
  ipv6: false
growpart:
  mode: auto
  devices: ['/dev/sda2']
  ignore_growroot_disabled: true
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: true
      dhcp-identifier: mac
