#cloud-config
local-hostname: vault
instance-id: vault
wait-on-network:
  ipv4: false
  ipv6: false
growpart:
  mode: auto
  devices: ['/dev/sda2']
  ignore_growroot_disabled: true
network:
  version: 2
  ethernets:
    ens192:
      addresses:
      - ${ip_address}/${netmask}
      gateway4: ${gateway}
      nameservers:
        addresses: [${nameservers}]